# keep any existing [build] section you have above …

[[redirects]]
  from = "/assets/loads.json"
  to = "https://script.google.com/macros/s/AKfycbzXfnH8m0LxiQ1rkqf7AJt9qmp1sok722xYMmwdS96RKwgWBOt2xLrBc-1FPTnIbHP91A/exec"
  status = 200
  force = true
