[[redirects]]
  from = "/assets/loads.json"
  to = "https://script.google.com/macros/s/AKfycbzXfnH8m0LxiQ1rkqf7AJt9qmp1sok722xYMmwdS96RKwgWBOt2xLrBc-1FPTnIbHP91A/exec?mode=compat"
  status = 200
  force = true

[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200